const charEmojiMap = {
    "villager": "\uD83D\uDC71",
    "vg": "\uD83D\uDC71",
    "drunk": "\uD83C\uDF7B",
    "seer": "\uD83D\uDC73",
    "harlot": "\uD83D\uDC8B",
    "beholder": "\uD83D\uDC41",
    "bh": "\uD83D\uDC41",
    "gunner": "\uD83D\uDD2B",
    "guardian angel": "\uD83D\uDC7C",
    "ga": "\uD83D\uDC7C",
    "fool": "\uD83C\uDCCF",
    "seer or fool": "¿\uD83D\uDC73or\uD83C\uDCCF?",
    "mason": "\uD83D\uDC77",
    "lone mason": "\u0031\uFE0F\u20E3\uD83D\uDC77",
    "detective": "\uD83D\uDD75",
    "det": "\uD83D\uDD75",
    "apprentice seer": "\uD83D\uDE47",
    "cultist hunter": "\uD83D\uDC82",
    "ch": "\uD83D\uDC82",
    "cupid": "🏹",
    "hunter": "🎯",
    "th": "🎯",
    "clumsy guy": "🤕",
    "clumsy": "🤕",
    "blacksmith": "⚒",
    "prince": "💍",
    "mayor": "🎖",
    "oracle": "🌀",
    "monarch": "👑",
    "pacifist": "☮️",
    "wise elder": "📚",
    "we": "📚",
    "sandman": "💤",
    "wolfman": "👱‍🌚",
    "martyr": "🔰",
    "alchemist": "🍵",
    "squire": "🛡",
    "beauty": "💅",
    "storm bringer": "🌩",
    "storm": "🌩",
    "traitor": "🖕",
    "wild child": "👶",
    "wc": "👶",
    "cursed": "😾",
    "black wolf": "🐺🌑",
    "werewolf": "🐺",
    "wolf": "🐺",
    "sorcerer": "🔮",
    "alpha wolf": "⚡️",
    "alpha": "⚡️",
    "wolfcub": "🐶",
    "lycan": "🐺🌝",
    "prowler": "🦉",
    "mystic": "☄️",
    "trickster": "🐑",
    "trickster wolf": "🐑",
    "fallen angel": "👼🐺",
    "tanner": "👺",
    "cultist": "👤",
    "cult": "👤",
    "thief": "😈",
    "puppet master": "🕴",
    "puppet": "🕴",
    "doppleganger": "🎭",
    "dg": "🎭",
    "serial killer": "🔪",
    "sk": "🔪",
    "arsonist": "🔥",
    "arso": "🔥",
    "necromancer": "⚰️",
    "necro": "⚰️"
  }

module.exports = charEmojiMap